### ISSUE TITLE
アンバーグリスの解図に関して

### ISSUE THREAD

**Issue by Rm7367** [komori-n/KomoringHeights#1]
## 環境 / Environment

- Binary Name: KomoringHeights-kh-v0.5.0 develop / Commits on May 3, 2022 compiled with clang++-10
- OS: Ubuntu 18.04.5 LTS (google colab)
- CPU: Intel(R) Xeon(R) CPU @ 2.20GHz
- RAM: 13 GB

## 説明 / Description

バグが発生する局面、エンジンオプションや期待動作を記載してください。
Please describe the issue and how to reproduce it (engine options, positions, ...).

作品名：アンバーグリス
手数：605
1s1l2l1K/1P1R2npp/1pg1k3l/pnsgg3n/2p1gn3/2S2rp1B/5p2b/PS7/4P1P2 b L3P4p 1
Options[USI_Hash] = 4096
Options[PostSearchCount] = 0

作意605手詰みに対し229手詰みを返します。
17手作意59香打に対し58香打で離れ、香を取らずに48玉以下228手目の39玉が自殺手で38龍で即詰み。

なお、Options[USI_Hash] = 10240とすると605手（ほぼ作意）で正常に解図します。

余談になりますが、アンバーグリス解図は
他のKHバージョンでも標準設定のOptions[PostSearchCount] = 400において受け方変化で作意より短い解答をする、
あるいは置換表の量で解図時間が極端に変わる等あやしげな挙動を示します。
[kh.log.gz](https://github.com/komori-n/KomoringHeights/files/9209942/kh.log.gz)

**Comment by komori-n** [comment]
反応が遅れてしまい申し訳ありません。ご報告ありがとうございます。

詰み手順の不安定さについてはとても根の深い問題のため、解決までに少し時間をください。次回メジャーバージョンアップ（0.6.0 or 1.0.0）にて修正予定です。

**Comment by komori-n** [comment]
修正が遅れてしまい申し訳ありません。v1.0.0にて経路探索の安定性が向上しました。作意605手に対し、619手詰（8枚駒余り）を返すようになりました。また、置換表サイズに依存した不安定な挙動についても改善しています。
