### ISSUE TITLE
受け方始まりの解図で bestmove resign を返すのは

### ISSUE THREAD

**Issue by Rm7367** [komori-n/KomoringHeights#2]
今の KomoringHeights に足りない機能、あると便利な機能を書いてください。
Please describe the feature you want.

受け方最長手順選択の原則に反すると考えます。

**Comment by komori-n** [comment]
不具合のご報告ありがとうございます。コード自体は受け方からスタートする局面にも対応していましたが、不具合で正しい手順を返せていませんでした。

次回のマイナーアップデート（0.5.1）で修正予定です。
