### ISSUE TITLE
不詰検出直前で無限ループ？

### ISSUE THREAD

**Issue by Rm7367** [komori-n/KomoringHeights#4]
## 環境 / Environment

    Binary Name: KomoringHeights v0.5.0
    OS: Ubuntu 18.04.5 LTS (google colab)
    CPU: Intel(R) Xeon(R) CPU @ 2.20GHz
    RAM: 13 GB

## 説明 / Description

Options[USI_Hash] = 10240
Options[PostSearchCount] = 400
Options[YozumePrintLevel] = 1

position 9/9/3k5/9/6B2/9/9/9/9 b 4G2S9P2rb2s4n4l9p 1
go mate infinite
info score cp -22400 depth 2 seldepth 83 time 13538246 nodes 5797755242 nps 250329 hashfull 657 currmove P\*6d pv P\*6d 6c7c

不詰検出間近と思われるところでHash使用量とPVが変わらない状況が続きます。

**Comment by Rm7367** [comment]
別の解図でも同様の現象がありました。
9/6k2/9/9/9/9/9/9/9 b R4GLr2b4s4n3l18p 1
[kh.log.gz](https://github.com/komori-n/KomoringHeights/files/9585217/kh.log.gz)

**Comment by komori-n** [comment]
反応遅れて申し訳ありません。v1.0.0 にて不具合は修正されました。両局面に対し、USI_Hash=30000で正しく不詰（checkmate nomate）を返すことを確認しました。
