### ISSUE TITLE
cp -18839でmate

### ISSUE THREAD

**Issue by Rm7367** [komori-n/KomoringHeights#6]
## 環境 / Environment

Binary Name: KomoringHeights v0.5.0
OS: Ubuntu 18.04.5 LTS (google colab)
CPU: Intel(R) Xeon(R) CPU @ 2.20GHz
RAM: 13 GB

## 説明 / Description

Options[USI_Hash] = 10240
Options[PostSearchCount] = 400
Options[YozumePrintLevel] = 1

position 7k1/9/9/9/9/9/9/9/9 b B2G2SL2P2rb2g2s4n3l16p 1
go mate infinite
info score cp -18839 depth 18 seldepth 122 time 17603155 nodes 10864653299 nps 537477 hashfull 731 currmove P\*2b pv P\*2b 2a3b B\*6e 3b2b L\*2i P\*2e G\*1c 2b1c G\*1d 1c1d 6e3b+ 1d2d 3b4b 2d3e S\*4d 3e4d S\*3c 4d4e
info score mate 4006 depth 0 seldepth 122 time 17604021 nodes 10865077185 nps 533094 hashfull 731 string kProvenState 2984 ProvenData{L\*2f/4006(0)/P2LS2BG2}
info score mate 4006 depth 37 seldepth 122 time 17640159 nodes 10896433179 nps 806621 hashfull 757 currmove L\*2f pv L\*2f B\*2b B\*4c R\*3b 2f2b+ 2a2b S\*2c 2b2c P\*2d 2c2d G\*2e 2d1c S\*1d 1c2b G\*2c 2b1a B\*2b 3b2b 2c2b 1a2b R\*8b R\*7b 1d1c+ 2b3a 1c2b 3a4a 2b3b 4a5a P\*5b 5a6b 8b7b+ 6b7b R\*7i P\*7c 4c5d+ 7b6a 5b5a+
info string mate_len=4000(0)
info score mate 0 depth 0 seldepth 122 time 17640712 nodes 10896736602 nps 793050 hashfull 758 string no yozume found
info string Failed to detect PV
info string research 6
checkmate L\*2f 2a3b G\*3c 3b3c G\*2c 3c4c

おそらくは不詰の裸玉解図において上記現象を確認しました。

**Comment by komori-n** [comment]
反応遅れてしまい大変申し訳ありません。v1.0.0 USI_Hash=30000 にて正しく不詰を返すようになりました。
